### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by Aditya-dom** [Velox0/libclr#3]
```
cd libclr/
./install.sh
zsh: ./install.sh: bad interpreter: /usr/bin/bash: no such file or directory
```
> error : `/install.sh: bad interpreter: /usr/bin/bash: no such file or directory`

Device: MacBook Pro M2 chip
Operating system: macOS Sonoma   `Version 14.2.1`

**Comment by velox0** [comment]
Can you tell me the output of `where bash`? Thanks!

**Comment by Aditya-dom** [comment]
@

> Can you tell me the output of `where bash`? Thanks!

@Velox0  yes sure
```
where bash
/bin/bash
```

**Comment by Aditya-dom** [comment]
Thanks buddy : ) @Velox0
